Added BusSchedule, BusRouteAssignments, and BusReservations entities
starlabspro-internship/pentasharp pull request #6
Opened 2024-11-04 08:21 UTC by rinesakuci

2024-11-04 17:00 UTC, oltahasimja submitted a review, later dismissed

2024-11-06 15:24 UTC, GentaSL commented on pentasharp/Models/Entities/BusReservations.cs
> +    {
add xml summaries https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags

2024-11-06 15:24 UTC, GentaSL commented on pentasharp/Models/Entities/BusRouteAssignments.cs
> +    {
add xml summaries https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags

2024-11-06 15:24 UTC, GentaSL commented on pentasharp/Models/Entities/BusRoutes.cs
> +    {
add xml summaries https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags

2024-11-06 15:25 UTC, GentaSL commented on pentasharp/Models/Entities/BusSchedule.cs
> +    {
add xml summaries https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags

2024-11-06 15:25 UTC, GentaSL commented on pentasharp/Models/Entities/Buses.cs
> +    {
add xml summaries https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags

2024-11-06 15:25 UTC, GentaSL requested changes
add missing summaries as required

2024-11-07 09:58 UTC, GentaSL approved these changes, later dismissed

2024-11-11 08:45 UTC, GentaSL approved these changes

2024-11-11 09:08 UTC, oltahasimja approved these changes

2024-11-11 09:09 UTC, merged